[package]
name = "test-program"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "1.18.2"

[dev-dependencies]
protosol = { path = "../" }
solana-sdk = "1.18.2"

[lib]
crate-type = ["cdylib", "lib"]